### ISSUE TITLE
Possible issue with how triggers are started

### ISSUE THREAD

**Issue by pascalw** [jenkinsci-transfer/multi-branch-project-plugin#24]
I noticed that when creating projects with this plugin the Github plugin doesn't create webhooks like it normally does on regular projects.

I've debugged this issue a bit and noticed that on multi branch projects the Github trigger `start` method is always called with `newInstance = false` whereas on regular projects the it's called with newInstance = true. Looking at the code I think this could possibly originate from [here](https://github.com/mjdetullio/multi-branch-project-plugin/blob/54d7e5ebde04a13469d96b883cb81ce11351164f/src/main/java/com/github/mjdetullio/jenkins/plugins/multibranch/FreeStyleMultiBranchProject.java#L964) where the start method is indeed called with `newInstance=false`.

What I'm confused about however is whether the triggers should be started from the parent project at all or if they should be started on each child project. In any case the behavior of starting triggers seems to be different in multi branch projects vs regular projects. @mjdetullio can you help me understand this issue? If this is an actual issue I would like to fix it but I first want to make sure I fully understand the issue.

**Comment by mjdetullio** [comment]
The call to ```Trigger#start``` is defined in ```AbstractProject``` so the only way to control the ```newInstance``` value is to set the updating by XML flag on the thread.  I haven't looked at the GitHub plugin to see how it uses this value, so I can't take any action on it for the time being.

**Comment by pascalw** [comment]
@mjdetullio `Trigger#start` is also claled by this plugin [here](https://github.com/mjdetullio/multi-branch-project-plugin/blob/54d7e5ebde04a13469d96b883cb81ce11351164f/src/main/java/com/github/mjdetullio/jenkins/plugins/multibranch/FreeStyleMultiBranchProject.java#L964). I'm not sure if its also called from `AbstractProject` still?

The problem is in any case that the `newInstance` parameter is always set to `false`. I think that to make multi branch projects behave similarly to regular projects we'd have to set that value to true when new branch projects are created. Do you think that's possible?

The Github plugin uses `newInstance` it as follows btw:

```java
public class GitHubPushTrigger extends Trigger<AbstractProject<?,?>> implements GitHubTrigger {
...
    public void start(AbstractProject<?,?> project, boolean newInstance) {
        super.start(project, newInstance);
        if (newInstance && getDescriptor().isManageHook()) {
            registerHooks();
        }
    }
...
}
```

**Comment by mjdetullio** [comment]
Yes but the trigger start in this plugin is only for the main project, not the individual branch projects.  Looks like maybe the update by XML flag might be required when the branch projects are updated.  It normally gets set when using the config.xml API but I don't see how this will stop existing triggers if they are removed.  Jenkins core doesn't seem to account for that either it appears.  If it does, I'm not sure how.

Perhaps I'll try to reuse the config.xml submission API now that things have been refactored a bit.

**Comment by pascalw** [comment]
> Yes but the trigger start in this plugin is only for the main project, not the individual branch projects.

Ah gotcha.

> Jenkins core doesn't seem to account for that either it appears. If it does, I'm not sure how.

I think you might be right it doesn't do that. I ran into something [similar](https://github.com/jenkinsci/ghprb-plugin/pull/64) a while ago.

> Perhaps I'll try to reuse the config.xml submission API now that things have been refactored a bit.

For short term if all that we need is the `updatingByXml` flag we could wrap updating branch projects in a  `Items.whileUpdatingByXml`.

**Comment by dinomite** [comment]
I think I'm seeing this issue as well—newly created branches (which are synced by the polling schedule) get a build triggered, but subsequent commits.  When editing the parent project's settings, I see the following in the log:

    Jul 05, 2015 12:42:29 PM WARNING org.kohsuke.stapler.RequestImpl$TypePair convertJSON
    'stapler-class' is deprecated: hudson.tasks.Shell
    Jul 05, 2015 12:42:29 PM WARNING org.kohsuke.stapler.RequestImpl$TypePair convertJSON
    'stapler-class' is deprecated: hudson.tasks.Shell
    Jul 05, 2015 12:42:29 PM WARNING org.kohsuke.stapler.RequestImpl$TypePair convertJSON
    'stapler-class' is deprecated: hudson.tasks.Mailer
    Jul 05, 2015 12:42:29 PM WARNING org.kohsuke.stapler.RequestImpl$TypePair convertJSON
    'stapler-class' is deprecated: com.cloudbees.jenkins.GitHubCommitNotifier
    Jul 05, 2015 12:42:29 PM WARNING com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleMultiBranchProject doConfigSubmit
    Unable to execute convertUpstreamBuildTrigger(Set)
    java.lang.NoSuchMethodException: hudson.model.AbstractProject.convertUpstreamBuildTrigger(java.util.Set)
        at java.lang.Class.getDeclaredMethod(Class.java:2009)
        at com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleMultiBranchProject.doConfigSubmit(FreeStyleMultiBranchProject.java:761)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
        at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:123)
        at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:120)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:114)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:85)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
        at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

The branches do get poked when a new commit is made:

    Jul 05, 2015 12:35:49 PM INFO com.cloudbees.jenkins.GitHubWebHook processGitHubPayload
    Received POST for https://github.com/dmassant/Forum-server
    Jul 05, 2015 12:35:49 PM INFO com.cloudbees.jenkins.GitHubWebHook processGitHubPayload
    Poked forum-server » develop
    Jul 05, 2015 12:35:49 PM INFO com.cloudbees.jenkins.GitHubWebHook processGitHubPayload
    Poked forum-server » feature/buzz-page
    Jul 05, 2015 12:35:49 PM INFO com.cloudbees.jenkins.GitHubWebHook processGitHubPayload
    Poked forum-server » feature/freshness-rework
    Jul 05, 2015 12:35:49 PM INFO com.cloudbees.jenkins.GitHubWebHook processGitHubPayload
    Poked forum-server » master

But no new builds are executed.

I haven't investigated much more than looking at the logs while kicking off builds, but I'm happy to investigate more and any direction would be good.

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32252
